### ISSUE TITLE
PLAYFRIIK!!! helpme!!

### ISSUE THREAD

**Issue by ElPresidentePro** [MCTyler/CrafterNexus#14]
Hello, my name is biitz and i have a problem.
My problen is the next http://gyazo.com/4a9b8f04102886124c410de907188199
in the image you see the EnderFurnace no cooked the items you have resolved problem?
@MCTyler @PlayFriik

**Comment by PlayFriik** [comment]
No I haven't resolved the problem.

**Comment by ElPresidentePro** [comment]
you can resolved in 3 hours and i pay you 5 Eur? pls pls pls i need ;(

**Comment by ElPresidentePro** [comment]
i Change the code but no resolved ;(

public class EnderFurnaceListener implements Listener {
    private final HashMap<GameTeam, Location> locations;
    private HashMap<String, VirtualFurnace> furnaces;

    public EnderFurnaceListener(AnniReloader plugin) {
        locations = new HashMap<>();
        furnaces = new HashMap<>();
        
        Bukkit.getScheduler().runTaskTimer(plugin, new Runnable() {
            @Override
            public void run() {
                for (VirtualFurnace f : furnaces.values())
                    f.g();
            }
        }, 0L, 1L);
    }

    public void setFurnaceLocation(GameTeam team, Location loc) {
        locations.put(team, loc);
    }

    @EventHandler
    public void onFurnaceOpen(PlayerInteractEvent e) {
        if (e.getAction() != Action.RIGHT_CLICK_BLOCK)
            return;
        
        Block b = e.getClickedBlock();
        if (b.getType() != Material.FURNACE)
            return;

        Location loc = b.getLocation();
        Player player = e.getPlayer();
        GameTeam team = PlayerMeta.getMeta(player).getTeam();
        if (team == null || !locations.containsKey(team))
            return;

        if (locations.get(team).equals(loc)) {
            e.setCancelled(true);
            EntityPlayer handle = ((CraftPlayer) player).getHandle();
            handle.openContainer(getFurnace(player));
            player.sendMessage(ChatColor.DARK_AQUA
                    + _("EF_MSG1"));
        }
    }

    @EventHandler
    public void onFurnaceBreak(BlockBreakEvent e) {
        if (locations.values().contains(e.getBlock().getLocation()))
            e.setCancelled(true);
    }

    private VirtualFurnace getFurnace(Player player) {
        if (!furnaces.containsKey(player.getName())) {
            EntityPlayer handle = ((CraftPlayer) player).getHandle();
            furnaces.put(player.getName(), new VirtualFurnace(handle));
        }
        return furnaces.get(player.getName());
    }

    private class VirtualFurnace extends TileEntityFurnace {
        public VirtualFurnace(EntityHuman entity) {
            world = entity.world;
        }

        @Override
        public boolean a(EntityHuman entity) {
            return true;
        }

        public int p() {
            return 0;
        }

        public net.minecraft.server.v1_8_R2.Block q() {
            return net.minecraft.server.v1_8_R2.Blocks.FURNACE;
        }

        @Override
        public void update() {

        }

        @Override
        public InventoryHolder getOwner() {
            return new InventoryHolder() {
                public Inventory getInventory() {
                    return new CraftInventoryFurnace(VirtualFurnace.this);
                }
            };
        }
    }
}

**Comment by ElPresidentePro** [comment]
i insert         e.setCancelled(true); in the IF

**Comment by ElPresidentePro** [comment]
you add my skype: osmanygon

**Comment by PlayFriik** [comment]
Okay, I will look into that tomorrow, if you are willing to pay 5€.

**Comment by MCTyler** [comment]
Thanks PlayFriik for taking this over...can you fork it and update it on your Git?

**Comment by ElPresidentePro** [comment]
Men i resolved bug no problem ty play friik
