### ISSUE TITLE
Player Leave Event

### ISSUE THREAD

**Issue by MCTyler** [MCTyler/CrafterNexus#4]
I need to add a event when a Player selects a team, then leaves...Their selection [doesn't] remain valid for that team. Canceable event? (Thinking to myself) (oops Sry...edited it)

**Comment by PlayFriik** [comment]
What you mean by that: "Canceable event"? Well you can get the player and remove from team, but it can break the game hardly, because then he/she can't join back anymore to the game probably..

**Comment by MCTyler** [comment]
Yea, but if a player is just browsing the lobby and selects a team, when they leave the lobby it needs to cancel their selection for that team unless they actually play the game. Right now the selection remains valid until the entire game resets.

**Comment by MCTyler** [comment]
Here's Libs's...See if you can tell why His works...

package me.libraryaddict.Hungergames.Events;

import org.bukkit.event.*;

public class ServerShutdownEvent extends Event implements Cancellable
{
    private static final HandlerList handlers;
    private boolean cancelled;
    
    public ServerShutdownEvent() {
        super();
        this.cancelled = false;
    }
    
    public static HandlerList getHandlerList() {
        return ServerShutdownEvent.handlers;
    }
    
    public HandlerList getHandlers() {
        return ServerShutdownEvent.handlers;
    }
    
    public boolean isCancelled() {
        return this.cancelled;
    }
    
    public void setCancelled(final boolean state) {
        this.cancelled = state;
    }
    
    static {
        handlers = new HandlerList();
    }
}

**Comment by PlayFriik** [comment]
Hmm, you can try to check that is the game running on player join..? if it is running then don't remove, but if it is not, then remove? I am looking into his code in the evening, because I am not at home today.

**Comment by MCTyler** [comment]
This Works! I'll commit it later..gotta run. Just add this to your PlayerListener.
   [code] /**
     *
     * @param event - Resets GameTeam When Player Leaves Lobby
     */
    @EventHandler
    public void leaveRemoveGameTeam(PlayerQuitEvent event) {
        Player player = event.getPlayer();
        PlayerMeta meta = PlayerMeta.getMeta(player);
        if (event.getPlayer().getWorld().getName().equals("lobby")) {
            if (meta.isAlive())
                meta.setAlive(false);
                    meta.setTeam(GameTeam.NONE);
        plugin.getSignHandler().updateSigns(meta.getTeam());
    }
}
[/code]
