### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by Lmmb74** [MCTyler/CrafterNexus#7]
When I try to compile the plugin with maven, I get this error:
[ERROR] /C:/Users/Lautaro/Desktop/Compile/CrafterNexus-master/src/main/java/org/
eodsteven/CrafterNexus/CrafterNexus.java:[573,42] cannot find symbol
[ERROR] symbol:   variable length
[ERROR] location: interface java.util.Collection<capture#1 of ? extends org.bukk
it.entity.Player>
[ERROR] /C:/Users/Lautaro/Desktop/Compile/CrafterNexus-master/src/main/java/org/
eodsteven/CrafterNexus/listeners/PlayerListener.java:[91,65] cannot find symbol
[ERROR] symbol:   variable length
[ERROR] location: interface java.util.Collection<capture#2 of ? extends org.bukk
it.entity.Player>

**Comment by MCTyler** [comment]
I don't think anyone has uploaded anything...Are you using Java 8?

**Comment by MCTyler** [comment]
I just ran it....
Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0


--- maven-jar-plugin:2.3.2:jar (default-jar) @ CrafterNexus ---
Building jar: /home/steve/NetBeansProjects/CrafterNexus/target/CrafterNexus.jar

--- maven-install-plugin:2.3.1:install (default-install) @ CrafterNexus ---
Installing /home/steve/NetBeansProjects/CrafterNexus/target/CrafterNexus.jar to /home/steve/.m2/repository/org/eodsteven/CrafterNexus/CrafterNexus/1.8.1/CrafterNexus-1.8.1.jar
Installing /home/steve/NetBeansProjects/CrafterNexus/pom.xml to /home/steve/.m2/repository/org/eodsteven/CrafterNexus/CrafterNexus/1.8.1/CrafterNexus-1.8.1.pom
------------------------------------------------------------------------
BUILD SUCCESS
------------------------------------------------------------------------
Total time: 29.533s
Finished at: Fri Jan 30 14:35:29 CST 2015
Final Memory: 8M/19M
------------------------------------------------------------------------

**Comment by PlayFriik** [comment]
[ERROR] symbol: variable length

Are you sure that there wasn't errors? Because as far I can see there is variable 'length', but it should be 'size()'..?

**Comment by MCTyler** [comment]
Don't use Bukkikt as a dependency, use craftbukkit and it will fix that. Sry if I had Bukkit in the Pom.xml.
