### ISSUE TITLE
1.8.3 version

### ISSUE THREAD

**Issue by Granik24** [MCTyler/CrafterNexus#8]
Hi guys,
will be this plugin available for version 1.8.3?

**Comment by MCTyler** [comment]
I was supposed to get help updating it but got none and I am stuck, Sry.

**Comment by PlayFriik** [comment]
MCTyler, can you update the MapLoader class file? I fixed error with chunk(s) positioning.

http://hastebin.com/uridixareq.avrasm

**Comment by MCTyler** [comment]
Ok, I commited it.

**Comment by MCTyler** [comment]
Fully Updated now.

**Comment by Granik24** [comment]
Thank you so much! I'll test it soon on my server :)
