### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by ElPresidentePro** [MCTyler/CrafterNexus#9]
Hello my name is osmany and i have a problem i have the error in MapLoader

**Comment by MCTyler** [comment]
You need to be more specific.

**Comment by ElPresidentePro** [comment]
No load the file MapLoader in other files

**Comment by PlayFriik** [comment]
Post screenshots please.

**Comment by ElPresidentePro** [comment]
http://gyazo.com/b18f5df12942ed58dc99c740f10617cb
http://gyazo.com/79736117faf76365179d5f8a06dd129a

**Comment by MCTyler** [comment]
That doesn't look like my code...can you help @PlayFriik ?

**Comment by PlayFriik** [comment]
No, everything is fine, just move your mouse to the underlined red MapRollback, then should appear some kind of "box" and select "rename". 

There is longer sentence probably in the Eclipse, but I am in the phone and I can't remember the full sentence.

**Comment by MCTyler** [comment]
Ok, Once you add the rename I'll close this issue. I no longer using this plugin so I'll leave it up to you all to maintain.

**Comment by MCTyler** [comment]
Alright, I made all the changes an updated to the latest Bukkit...Build is good and renamed file 1.8.2.
